# Generated by Django 5.0.6 on 2025-12-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_education_alter_blogpost_id_alter_contactmessage_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('design', 'Design'), ('database', 'Database'), ('services', 'Services'), ('tools', 'Tools'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
